name: Central Sonar Scanner

on:
  workflow_dispatch:

jobs:
  scan-all:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip curl

      - name: Get list of all repos
        run: |
          gh repo list ${{ github.repository_owner }} --limit 100 --json name -q '.[].name' > repos.txt

      - name: Loop & Scan each repo
        run: |
          mkdir tmp
          while read repo; do
            echo "🔍 Scanning $repo..."
            cd tmp

            # Clone shallowly
            git clone --depth=1 https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository_owner }}/$repo repo || { echo "❌ Failed to clone"; cd ..; continue; }

            cd repo

            # Detect language
            if [ -f "pom.xml" ]; then
              LANG="java"
              SRC="src"
            elif [ -f "package.json" ]; then
              LANG="js"
              SRC="."
            elif ls *.py &>/dev/null; then
              LANG="py"
              SRC="."
            else
              echo "⚠️  Unknown language in $repo — skipping"
              cd ../..
              rm -rf repo
              continue
            fi

            echo "✅ Detected language: $LANG"

            # Generate sonar config
            cat <<EOF > sonar-project.properties
sonar.projectKey=${repo}
sonar.sources=${SRC}
sonar.language=${LANG}
EOF

            # Download and run sonar-scanner
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
            unzip -q sonar-scanner.zip
            ./sonar-scanner-*/bin/sonar-scanner \
              -Dsonar.projectKey=$repo \
              -Dsonar.sources=${SRC} \
              -Dsonar.host.url=https://your-sonarqube-server \
              -Dsonar.login=$SONAR_TOKEN || echo "⚠️  Sonar failed for $repo"

            cd ../..
            rm -rf repo
          done < repos.txt
