jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip curl

      - name: Get all repos in the organization
        run: |
          gh repo list ${{ github.repository_owner }} --limit 100 --json name -q '.[].name' > repos.txt

      - name: Scan each repo
        run: |
          mkdir workspace && cd workspace
          while read repo; do
            echo "🔍 Cloning and scanning $repo..."
            git clone --depth=1 https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository_owner }}/$repo repo || {
              echo "❌ Failed to clone $repo — skipping"
              continue
            }

            cd repo

            # Detect language and source directory
            if [ -f "pom.xml" ]; then
              LANG="java"
              SRC="src"
            elif [ -f "package.json" ]; then
              LANG="js"
              SRC="."
            elif ls *.py &>/dev/null; then
              LANG="py"
              SRC="."
            else
              echo "⚠️  Could not detect language in $repo — skipping"
              cd ..
              rm -rf repo
              continue
            fi

            echo "✅ Language: $LANG, Source: $SRC"

            # Generate sonar-project.properties dynamically
            cat <<EOF > sonar-project.properties
sonar.projectKey=$repo
sonar.sources=$SRC
sonar.language=$LANG
EOF

            # Download and run sonar-scanner
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
            unzip -q sonar-scanner.zip
            ./sonar-scanner-*/bin/sonar-scanner \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.host.url=https://your-sonarqube-server || echo "⚠️  Sonar scan failed for $repo"

            cd ..
            rm -rf repo sonar-scanner* sonar-project.properties
          done < ../repos.txt
